### ISSUE TITLE
[BUG] When on normal mode my game runs fine for a few minutes then it lags.

### ISSUE THREAD

**Issue by ChewyGogurt** [CalaMariGold/Rebirth-Of-The-Night#116]
**Describe the bug**
So when i play on normal mode my game runs really smooth. Then after a bit there will be a delay like when i hit a mob or an animal. There is also a delay between me breaking a block and it actually disappearing. 

**To Reproduce**
Specs: 
CPU - AMD FX-6300 @3.75
GPU - 1050 TI
RAM - 8gb ddr3 @1866
Samsung 860 evo ssd

idk if it is just me but just go into normal mode survival and go near a bunch of entities or mobs then try and mine or hit them. 

**Expected behavior**
There should be a delay, you hit the mob it absorbs the damage but seems to be moving slow or choppy. The block goes away for a split second before reappearing and then after a moment it drops. 
**Screenshots**
Cant really do that

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Single player
 - Version the world was created on: Either 2.76 or 2.76.1, im pretty sure it was the one right before 2.76.2

**Additional context**

im guessing that it is all the entities or some kind of loading error.

**Comment by 1866** [comment]
Mechanical hard disk？







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChewyGogurt"<notifications@github.com&gt;; 
发送时间: 2020年3月10日(星期二) 上午8:15
收件人: "CalaMariGold/Rebirth-Of-The-Night"<Rebirth-Of-The-Night@noreply.github.com&gt;; 
抄送: "1866、"<1005860486@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: [CalaMariGold/Rebirth-Of-The-Night] [BUG] When on normal mode my game runs fine for a few minutes then it lags. (#116)




Describe the bug
 So when i play on normal mode my game runs really smooth. Then after a bit there will be a delay like when i hit a mob or an animal. There is also a delay between me breaking a block and it actually disappearing.
 
To Reproduce
 Specs:
 CPU - AMD FX-6300 @3.75
 GPU - 1050 TI
 RAM - 8gb ddr3 @1866
 
idk if it is just me but just go into normal mode survival and go near a bunch of entities or mobs then try and mine or hit them.
 
Expected behavior
 There should be a delay, you hit the mob it absorbs the damage but seems to be moving slow or choppy. The block goes away for a split second before reappearing and then after a moment it drops.
 Screenshots
 Cant really do that
 
Info (please complete the following information):
  
Modpack Version: 2.76.2
 
Server or Singleplayer: Single player
 
Version the world was created on: Either 2.76 or 2.76.1, im pretty sure it was the one right before 2.76.2
  
Additional context
 
im guessing that it is all the entities or some kind of loading error.

**Comment by CalaMariGold** [comment]
Not really much information here. Try reinstalling the pack and make sure you have optifine

**Comment by 1866** [comment]
okay




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mari"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 凌晨2:44
收件人: "CalaMariGold/Rebirth-Of-The-Night"<Rebirth-Of-The-Night@noreply.github.com&gt;; 
抄送: "1866、"<1005860486@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [CalaMariGold/Rebirth-Of-The-Night] [BUG] When on normal mode my game runs fine for a few minutes then it lags. (#116)





 
Not really much information here. Try reinstalling the pack and make sure you have optifine
