### ISSUE TITLE
[BUG/EXPLOIT] Infinite bone meal with chalk

### ISSUE THREAD

**Issue by Eksekk** [CalaMariGold/Rebirth-Of-The-Night#143]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the bug**
Placing and mining chalk over and over lets you get infinite bone meal from fossils that drop randomly. Even worse, chalk drop is not consumed when fossils drop.

**To Reproduce**
Place and mine chalk over and over until you get fossils.

**Expected behavior**
Only chalk that is placed on world generation gives fossils.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.76.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
I can't think of a good way to fix this. Maybe the other devs can give their input on this.

**Comment by spyroman** [comment]
You could simply create a near identical chalk block that is what drops from the current chalk block (those that spawn on world generation). Just have it so that new block does not drop fossils when mined. Perhaps you would like to name the original chalk "Preserved Chalk" or something to signify it's a block that may have fossils (only really matters for silk touch).

Either that or give chalk 'gravel dropping flint' mechanics where if it drops fossils, it doesn't drop a chalk block as well.

**Comment by CalaMariGold** [comment]
> Either that or give chalk 'gravel dropping flint' mechanics where if it drops fossils, it doesn't drop a chalk block as well.

This would be ideal, but not able to be accomplished. See, this doesn't occur for just chalk, it's ALL stone. Chalk is easy because you don't need silk touch.

MAYBE it's possible with CraftTweaker scripting, since I'm fairly sure it can edit block drops, but I'm not sure if it can edit block drops based on what we need. We may be able to do it by completely redoing how fossils/stone is dropped. I know for a fact the block drops mod we have doesn't have that sort of capability.

I think the best bet is to open an issue on the UGB's GitHub and hope they fix it.

**Comment by kil0byt3** [comment]
Opened issue with UGB, waiting

**Comment by kil0byt3** [comment]
Solved via https://github.com/Aang23/UndergroundBiomesConstructs/commit/b881b49fa5a47e96b11cde92e63ffb801f7ce1f7
