### ISSUE TITLE
[CRASH] biomes o' plenty & charm causing a crash when walking into a village.

### ISSUE THREAD

**Issue by mikzul** [CalaMariGold/Rebirth-Of-The-Night#232]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
A clear and concise description of what happened when you crash. Also, tell us if it continues to crash on world join or if it was a one time thing.

Walking around, crash related to "Charm, Biomes o' Plenty". Because of a village.

**To Reproduce**
Walk into a village.
**Crash Log**
Click "Get Link" from the crash and paste it here. Or post the log if it's a server.
http://txt.do/14ynm
**Info (please complete the following information):**
 - Modpack Version: 2.77
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 2.77

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
"exception ticking world"

**Comment by SandwichHorror** [comment]
It's due to a reading error between Village Names and Rats. If you go to the rats config and 

`# True if pet shops can spawn in villages [default: true]
B:"Village Pet Shops"=false`
set that to **true**, the crash will stop. This will be default (and the slightly buggy pet shops will be enabled) in 2.77.1 until rats or village names fixes the incompatibility.
