### ISSUE TITLE
[Suggestion] Adding some extra mods.

### ISSUE THREAD

**Issue by AdityaKumar5155** [CalaMariGold/Rebirth-Of-The-Night#364]
Hey,
If possible can you add some mods like OreExcavation? They are now getting more common in the latest modpacks like CrackPack, Astroblock, etc.
Don't mind if not possible, it is a just a suggestion thread.

**Comment by democat3457** [comment]
Due to other methods of multiblock mining like tnt, mining charges, giants pickaxe, etc, that would be a no. (Also, post on discord below)
<img width="595" alt="Screen Shot 2020-05-31 at 7 24 04 PM" src="https://user-images.githubusercontent.com/32407067/83366396-70aad880-a374-11ea-8318-426e6049e44d.png">
